name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name : List Dir
      run : ls -l /home/runner/work/TestFileAccess/TestFileAccess/target
  #  - uses: actions/download-artifact@v1
  #    with:
  #     name: ActionDemo-0.0.1-SNAPSHOT.jar
  #     path: target
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    
  #  - run: cat ActionDemo-0.0.1-SNAPSHOT.jar
    - uses: actions/upload-artifact@v1
      with:
       name: ActionDemo-BUILD_NUMBER.jar
       path: target/ActionDemo-0.0.1-SNAPSHOT.jar
       
   
